- name: Install utils packages
  become: yes
  become_user: root
  apt:
    name:
    - htop
    - iotop
    - chromium-browser
    - indicator-cpufreq
    - curl
    - wget
    - mc
    - tmux
    - gpaste
    - xsel
    - redshift-gtk
    - geoclue-2.0
    - apt-file
    - snapd
    - lm-sensors

- name: Install development packages
  become: yes
  become_user: root
  apt:
    names:
    - sqlite
    - postgresql-client
    - libxml2-dev
    - libxslt-dev
    - chromium-chromedriver
    - build-essential
    - libssl-dev
    - direnv
    - virtualbox
    - sshpass
    - pwgen

- name: Install tmux plugin manager
  git:
    repo: https://github.com/tmux-plugins/tpm.git
    dest: '{{ home }}/.tmux/plugins/tpm'
    depth: 1

- name: Install snap packages
  become: yes
  become_user: root
  snap:
    name:
      - vscode
      - insomnia
    classic: yes

- name: Clone fzf
  git:
    repo: https://github.com/junegunn/fzf.git 
    dest: '{{ home }}/.fzf'
    depth: 1

- name: Install fzf
  command: '{{ home }}/.fzf/install'

