- name: Uninstall old packages
  become: yes
  become_user: root
  apt:
    state: absent
    name: '{{ item }}'
  with_items:
    - docker
    - docker-engine

- name: Install necessary packs
  become: yes
  become_user: root
  apt:
    name: '{{ item }}'
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common

- name: Add apt key
  become: yes
  become_user: root
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg

- name: Add docker repo
  become: yes
  become_user: root
  apt_repository:
    repo: 'deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ubuntu_release }} stable'

- name: Install docker
  become: yes
  become_user: root
  apt:
    name: '{{ item }}'
  with_items:
    - docker.io
    - docker-compose

- name: Add docker group
  become: yes
  become_user: root
  user:
    name: '{{ user }}'
    groups: docker
    append: yes
