- name: Uninstall old packages
  become: yes
  become_user: root
  apt:
    state: absent
    name: '{{ item }}'
  with_items:
    - docker
    - docker-engine

- name: Install necessary packs
  become: yes
  become_user: root
  apt:
    name: '{{ item }}'
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common

- name: Add apt key
  become: yes
  become_user: root
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg

- name: Add docker repo
  become: yes
  become_user: root
  apt_repository:
    repo: 'deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ubuntu_release }} stable'

- name: Install docker
  become: yes
  become_user: root
  apt:
    name: '{{ item }}'
  with_items:
    - docker-ce
    
- name: Install Docker Compose
  become: yes
  become_user: root
  get_url:
    url: "https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-Linux-x86_64"
    dest: "/usr/local/bin/docker-compose"
    force: true
    owner: "root"
    group: "root"
    mode: "0755"

- name: Add docker group
  become: yes
  become_user: root
  user:
    name: '{{ user }}'
    groups: docker
    append: yes
