- name: Download node installation script
  get_url:
    url: https://deb.nodesource.com/setup_6.x
    dest: /tmp/nodesource_setup.sh

- name: Run script
  become: yes
  command: bash /tmp/nodesource_setup.sh

- name: Delete script
  file:
    path: /tmp/nodesource_setup.sh
    state: absent

- name: Add yarn key
  become: yes
  apt_key:
    url: https://dl.yarnpkg.com/debian/pubkey.gpg

- name: Add yarn repo
  become: yes
  command: bash -c 'echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list'

- name: Update apt cache
  become: yes
  action: apt update_cache=yes

- name: Install packages
  become: yes
  apt:
    name: '{{ item }}'
  with_items:
    - nodejs
    - yarn
