- name: Install php packages
  become: yes
  apt:
    name: '{{ item }}'
  with_items:
    - php
    - php-xml
    - php-json
    - php-xdebug

- name: Download composer
  get_url:
    url: https://getcomposer.org/download/1.4.2/composer.phar
    dest: '{{ home }}/.local/bin/composer'
    checksum: sha1:4400106431775fc9fc45acfb875b6e34ab3fea62

- name: Add eXecute mode
  file:
    path: '{{ home }}/.local/bin/composer'
    mode: 0755

- name: Download psyshell
  get_url:
    url: https://git.io/psysh
    dest: '{{ home }}/.local/bin/psysh'
    # checksum: sha1:4400106431775fc9fc45acfb875b6e34ab3fea62

- name: Add eXecute mode
  file:
    path: '{{ home }}/.local/bin/psysh'
    mode: 0755

- name: Download phpcs
  get_url:
    url: https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar
    dest: '{{ home }}/.local/bin/phpcs'
    # checksum: sha1:4400106431775fc9fc45acfb875b6e34ab3fea62

- name: Add eXecute mode
  file:
    path: '{{ home }}/.local/bin/phpcs'
    mode: 0755
