- name: Add python3.6 repo
  become: yes
  apt_repository:
    repo: 'ppa:jonathonf/python-3.6'

- name: Install packages
  become: yes
  apt:
    name: "{{ item }}"
    update_cache: yes
  with_items:
    - python-iniparse
    - python-dev
    - python3.6
    - python3.6-dev
    - virtualenv
    - virtualenvwrapper
    - python3-pip  # Todo: install pip3.6

- name: Install global packages
  become: no
  pip:
    name: pipenv
    executable: pip3
    extra_args: --user
