- name: Add python3.6 repo
  become: yes
  apt_repository:
    repo: 'ppa:jonathonf/python-3.6'
    codename: 'xenial'

- name: Update apt cache
  become: yes
  action: apt update_cache=yes

- name: Install packs
  become: yes
  action: apt name={{ item }}
  with_items:
    - python-iniparse
    - python-dev
    - python3.6
    - python3.6-dev
    - virtualenv
    - virtualenvwrapper
    - python3-pip

- name: Install global packages
  become: no
  pip:
    name: pipenv
    executable: pip3
    extra_args: --user
