- name: Install zsh
  become: yes
  action: apt name={{ item }}
  with_items:
    - zsh

- name: Change default shell
  become: yes
  shell: usermod -s /bin/zsh {{ username }}

- name: Clone zsh repo
  git:
    repo: git://github.com/robbyrussell/oh-my-zsh.git
    dest: ~/.oh-my-zsh
