- name: Install docker
  become: yes
  become_user: root
  apt:
    name:
      - docker.io
      - docker-compose

- name: Add docker group
  become: yes
  become_user: root
  user:
    name: '{{ user }}'
    groups: docker
    append: yes
