- name: Install git
  become: yes
  become_user: root
  apt:
    update_cache: yes
    name:
    - git
    - tig

- name: Config git editor
  git_config:
    name: core.editor
    scope: global
    value: vim

- name: Config git push strategy
  git_config:
    name: push.default
    scope: global
    value: simple

- name: Config git user name
  git_config:
    name: user.name
    scope: global
    value: "Egor Litvinov"

- name: Config git user email
  git_config:
    name: user.email
    scope: global
    value: yegor.litvinov@yandex.ru
