- name: Install utils packages
  become: yes
  become_user: root
  apt:
    update_cache: yes
    name:
    - htop
    - iotop
    # TODO:
    # Sometimes live tests are fails in chromium
    # Installing google-chrome helps
    - chromium-browser
    - chromium-chromedriver
    - curl
    - wget
    - mc
    - apt-file
    - snapd
    - lm-sensors
    - traceroute
    - sqlite
    - postgresql-client
    - libxml2-dev
    - libxslt-dev
    - build-essential
    - libssl-dev
    - direnv
    - sshpass
    - pwgen
    - postgresql-common
    - libpq-dev
    - unzip
    - imagemagick
    - jq

- name: Clone fzf
  git:
    repo: https://github.com/junegunn/fzf.git
    dest: '{{ home }}/.fzf'
    depth: 1

- name: Install fzf
  command: '{{ home }}/.fzf/install --completion --key-bindings --update-rc'

- name: Configure max user watches
  become: yes
  become_user: root
  sysctl:
    name: fs.inotify.max_user_watches
    value: '524288'
    state: present
