- name: Install utils packages
  become: yes
  become_user: root
  apt:
    name:
    - htop
    - iotop
    - chromium-browser
    - chromium-chromedriver
    - curl
    - wget
    - mc
    - apt-file
    - snapd
    - lm-sensors
    - traceroute
    - sqlite
    - postgresql-client
    - libxml2-dev
    - libxslt-dev
    - build-essential
    - libssl-dev
    - direnv
    - sshpass
    - pwgen
    - python3-dev
    - python3-pip

- name: Clone fzf
  git:
    repo: https://github.com/junegunn/fzf.git 
    dest: '{{ home }}/.fzf'
    depth: 1

- name: Install fzf
  command: '{{ home }}/.fzf/install --completion --key-bindings --update-rc'
