- name: Download node installation script
  get_url:
    url: 'https://deb.nodesource.com/setup_{{ node_version }}.x'
    dest: /tmp/nodesource_setup.sh

- name: Run script
  become: yes
  become_user: root
  command: bash /tmp/nodesource_setup.sh

- name: Delete script
  file:
    path: /tmp/nodesource_setup.sh
    state: absent

- name: Add yarn key
  become: yes
  become_user: root
  apt_key:
    url: https://dl.yarnpkg.com/debian/pubkey.gpg

- name: Add yarn repo
  become: yes
  become_user: root
  apt_repository:
    repo: deb https://dl.yarnpkg.com/debian/ stable main

- name: Update apt cache
  become: yes
  become_user: root
  action: apt update_cache=yes

- name: Install node
  become: yes
  become_user: root
  apt:
    name: 
    - nodejs
    - yarn
