- name: Install python packages
  become: yes
  become_user: root
  apt:
    update_cache: yes
    name:
    - python3-dev
    - python3-pip
    - python3-venv

- name: python3 is python by default
  become: yes
  become_user: root
  alternatives:
    name: python
    path: /usr/bin/python3
    link: /usr/bin/python

- name: Install pip packages
  pip:
    executable: pip3
    name:
      - pipenv
      - black
      - flake8
    extra_args: --user

- name: Download awscli version 1
  unarchive:
    src: https://s3.amazonaws.com/aws-cli/awscli-bundle.zip
    dest: /tmp/
    remote_src: yes

- name: Install awscli
  command: /tmp/awscli-bundle/install -b {{ home }}/.local/bin/awscli
