- name: Install vim packages
  become: yes
  become_user: root
  apt:
    name:
    - vim

- name: Copy config
  copy:
    src: .vimrc
    dest: '{{ home }}/.vimrc'

- name: Create autoload directory
  file:
    path: '{{ home }}/.vim/autoload/'
    state: directory
    mode: '0755'

- name: Install plugin manager
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: '{{ home }}/.vim/autoload/plug.vim'
