- name: Install packages
  become: yes
  action: apt name={{ item }}
  with_items:
    - zsh

- name: Change default shell
  become: yes
  shell: usermod -s /bin/zsh {{ username }}

# TODO: Figure out, why does it crashe
# - name: Install Oh My Zsh
#   shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
