- name: Create fonts dir
  file:
    path: '{{ home }}/.fonts'
    state: directory
    mode: 0755

- name: Fira Code font
  unarchive:
    src: https://codeload.github.com/tonsky/FiraCode/zip/master
    dest: '{{ home }}/.fonts'
    remote_src: yes

- name: Source code pro
  unarchive:
    src: https://codeload.github.com/adobe-fonts/source-code-pro/zip/variable-fonts
    dest: '{{ home }}/.fonts/'
    remote_src: yes

- name: Rebuild font cache
  command: fc-cache
