- name: Add input group
  become: yes
  become_user: root
  user:
    name: '{{ user }}'
    groups: input
    append: yes

- name: Install packages for gestures
  become: yes
  become_user: root
  apt:
    name:
      - xdotool
      - wmctrl
      - libinput-tools
      
- name: Clone libinput-gestures
  git:
    repo: https://github.com/bulletmark/libinput-gestures.git
    path: '{{ home }}/.tmp/libinput-gestures/'
    depth: 1

- name: Install libinput-gestures
  become: yes
  become_user: root
  make:
    chdir: '{{ home }}/.tmp/libinput-gestures/'
    args: install

- name: Start libinput-gestures
  command: "libinput-gestures-setup autostart && libinput-gestures-setup start"

- name: Copy gestures config
  file:
      name: libinput-gestures.conf
      path: '{{ home }}/.confing/libinput-gestures.conf'
