- name: Config git editor
  git_config:
    name: core.editor
    scope: global
    value: vim

- name: Config git push strategy
  git_config:
    name: push.default
    scope: global
    value: simple
