- name: Install vim packages
  become: yes
  become_user: root
  apt:
    name:
    - vim

- name: Copy config
  file:
      name: vimrc
      dst: '{{ home_dir }}/.vimrc'

# TODO: install plugin manager
