- hosts: localhost
  tasks:

  - name: Add python3.6 repo
    sudo: yes
    apt_repository:
      repo: 'ppa:jonathonf/python-3.6'
      codename: 'xenial'

  - name: Update apt cache
    sudo: yes
    action: apt update_cache=yes

  - name: Install packs
    sudo: yes
    action: apt name={{ item }}
    with_items:
      - python-iniparse
      - python-dev
      - python3.6
      - python3.6-dev
      - virtualenv
      - virtualenvwrapper
