- hosts: localhost
  tasks:

  - name: Update apt cache
    become: yes
    action: apt update_cache=yes

  - name: Install packages
    become: yes
    action: apt name={{ item }}
    with_items:
      - git
      - mercurial
      - tortoisehg

  - name: Config git editor
    git_config:
      name: core.editor
      scope: global
      value: vim

  - name: Config git push strategy
    git_config:
      name: push.default
      scope: global
      value: simple
